# # docker-compose.yml



# services:
#   qdrant:
#     image: qdrant/qdrant:latest
#     ports:
#       - "6333:6333"
#     volumes:
#       - qdrant_data:/qdrant/storage
#     restart: always
#     networks:
#       - private-gpt_default

#   ingestor:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     command: python ingest.py
#     environment:
#       - QDRANT_URL=http://qdrant:6333
#       # --- CAMBIO CLAVE ---
#       - OLLAMA_BASE_URL=http://10.1.0.176:11434
#     depends_on:
#       - qdrant

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     ports:
#       - "8000:8000"
#     environment:
#       - QDRANT_URL=http://qdrant:6333
#       # --- Y TAMBIÉN AQUÍ ---
#       - OLLAMA_BASE_URL=http://10.1.0.176:11434
#     depends_on:
#       - ingestor
#     restart: always

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#     ports:
#       - "8501:8501"
#     environment:
#       - API_URL=http://backend:8000/chat
#     depends_on:
#       - backend
#     restart: always
#     networks:
#       - private-gpt_default

# networks:
#   private-gpt_default:
#     external: true

# volumes:
#   qdrant_data:

# docker-compose.yml (Versión Corregida para Servidor)

# docker-compose.yml (Versión Corregida para Servidor, sin Healthcheck)

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    # AÑADIDO: Variable de entorno para asegurar que el puerto HTTP esté activo
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: always
    networks:
      - private-gpt_default

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python ingest.py
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_BASE_URL=http://10.1.0.176:11434
    depends_on:
      - qdrant
    networks: # <-- CAMBIO FUNDAMENTAL: Conectado a la red
      - private-gpt_default
    restart: on-failure # <-- AÑADIDO: Estrategia de reintento simple

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_BASE_URL=http://10.1.0.176:11434
    depends_on:
      - ingestor
    restart: always
    networks: # <-- CAMBIO FUNDAMENTAL: Conectado a la red
      - private-gpt_default

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - API_URL=http://backend:8000/chat
  #   depends_on:
  #     - backend
  #   restart: always
  #   networks:
  #     - private-gpt_default

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # 1. Asegúrate de que los puertos NO estén expuestos directamente
    # ports:
    #   - "8501:8501"
    environment:
      - API_URL=http://backend:8000/chat
    depends_on:
      - backend
    restart: always
    networks:
      - private-gpt_default # O la red que estés usando
    # 2. Añade estas etiquetas para que Traefik lo gestione
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`chatbot.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8501"

networks:
  private-gpt_default:
    external: true

volumes:
  qdrant_data:

